// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Student.proto

package com.mikey.grpcstream;

public interface RequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.mikey.grpc.Request)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string username = 1;</code>
   */
  java.lang.String getUsername();
  /**
   * <code>string username = 1;</code>
   */
  com.google.protobuf.ByteString
      getUsernameBytes();
}
