// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Student.proto

package com.mikey.grpcstream;

public final class StudentProto {
  private StudentProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_mikey_grpc_Request_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_mikey_grpc_Request_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_mikey_grpc_Response_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_mikey_grpc_Response_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_mikey_grpc_StudentResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_mikey_grpc_StudentResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_mikey_grpc_StudentRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_mikey_grpc_StudentRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_mikey_grpc_StudentResponseList_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_mikey_grpc_StudentResponseList_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_mikey_grpc_StreamRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_mikey_grpc_StreamRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_mikey_grpc_StreamResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_mikey_grpc_StreamResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\rStudent.proto\022\016com.mikey.grpc\"\033\n\007Reque" +
      "st\022\020\n\010username\030\001 \001(\t\"\034\n\010Response\022\020\n\010real" +
      "name\030\002 \001(\t\":\n\017StudentResponse\022\014\n\004name\030\001 " +
      "\001(\t\022\013\n\003age\030\002 \001(\005\022\014\n\004city\030\003 \001(\t\"\035\n\016Studen" +
      "tRequest\022\013\n\003key\030\001 \001(\t\"O\n\023StudentResponse" +
      "List\0228\n\017studentResponse\030\001 \003(\0132\037.com.mike" +
      "y.grpc.StudentResponse\"%\n\rStreamRequest\022" +
      "\024\n\014request_info\030\001 \001(\t\"\'\n\016StreamResponse\022" +
      "\025\n\rresponse_info\030\001 \001(\t2\336\002\n\016StudentServic" +
      "e\022L\n\025GetRealNameByUserName\022\027.com.mikey.g" +
      "rpc.Request\032\030.com.mikey.grpc.Response\"\000\022" +
      "O\n\017GetStudentByAge\022\027.com.mikey.grpc.Requ" +
      "est\032\037.com.mikey.grpc.StudentResponse\"\0000\001" +
      "\022^\n\022GetStudentByStream\022#.com.mikey.grpc." +
      "StudentResponseList\032\037.com.mikey.grpc.Stu" +
      "dentResponse\"\000(\001\022M\n\006BiTalk\022\035.com.mikey.g" +
      "rpc.StreamRequest\032\036.com.mikey.grpc.Strea" +
      "mResponse\"\000(\0010\001B&\n\024com.mikey.grpcstreamB" +
      "\014StudentProtoP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_com_mikey_grpc_Request_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_mikey_grpc_Request_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_mikey_grpc_Request_descriptor,
        new java.lang.String[] { "Username", });
    internal_static_com_mikey_grpc_Response_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_com_mikey_grpc_Response_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_mikey_grpc_Response_descriptor,
        new java.lang.String[] { "Realname", });
    internal_static_com_mikey_grpc_StudentResponse_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_com_mikey_grpc_StudentResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_mikey_grpc_StudentResponse_descriptor,
        new java.lang.String[] { "Name", "Age", "City", });
    internal_static_com_mikey_grpc_StudentRequest_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_com_mikey_grpc_StudentRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_mikey_grpc_StudentRequest_descriptor,
        new java.lang.String[] { "Key", });
    internal_static_com_mikey_grpc_StudentResponseList_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_com_mikey_grpc_StudentResponseList_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_mikey_grpc_StudentResponseList_descriptor,
        new java.lang.String[] { "StudentResponse", });
    internal_static_com_mikey_grpc_StreamRequest_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_com_mikey_grpc_StreamRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_mikey_grpc_StreamRequest_descriptor,
        new java.lang.String[] { "RequestInfo", });
    internal_static_com_mikey_grpc_StreamResponse_descriptor =
      getDescriptor().getMessageTypes().get(6);
    internal_static_com_mikey_grpc_StreamResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_mikey_grpc_StreamResponse_descriptor,
        new java.lang.String[] { "ResponseInfo", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
